// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

type Module struct {
	t0       []any
	elements [][]any
	_env     Xenv
}

func New(v0 Xenv) *Module {
	m := new(Module)
	m._env = v0
	m.t0 = make([]any, 32)
	m.elements = [][]any{{fn1}, {m.fn0}}
	copy(m.t0[i32(16):], m.elements[0])
	copy(m.t0[i32(17):], m.elements[1])
	if i, ok := any(v0).(interface {
		Init(any)
	}); ok {
		i.Init(m)
	}
	return m
}

type Xenv = interface {
	Xjstimes3(v0 int32) int32
}

func (m *Module) fn0(v0 int32) int32 {
	return m._env.Xjstimes3(v0)
}
func fn1(v0 int32) int32 {
	return v0 + v0
}
func (m *Module) Xtimes2(v0 int32) int32 {
	t0 := m.t0[uint(i32(16))].(func(int32) int32)(v0)
	return t0
}
func (m *Module) Xtimes3(v0 int32) int32 {
	t0 := m.t0[uint(i32(17))].(func(int32) int32)(v0)
	return t0
}

//go:nosplit
func i32(x int32) int32 { return x }
