package main

import (
	"bytes"
	"errors"
	"go/format"
	"html/template"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

//go:generate go test -run translate -args -unsafe
//go:generate go test -run translate

func Test_translate(t *testing.T) {
	tests := []string{"fib", "loops", "memory", "primes", "recursion", "stack", "table", "trig"}
	*nanbox = false
	for _, name := range tests {
		t.Run(name, func(t *testing.T) {
			path := "testdata/" + name + "/" + name

			in, err := os.Open(path + ".wasm")
			if err != nil {
				t.Fatal(err)
			}
			defer in.Close()

			var out bytes.Buffer
			err = translate(in, &out)
			if err != nil {
				t.Fatal(err)
			}

			err = os.WriteFile(path+".go", out.Bytes(), 0644)
			if err != nil {
				t.Fatal(err)
			}
		})
	}
}

func Test_regression(t *testing.T) {
	tests := []string{"tee_self_loop", "select_effect", "store_grow"}
	for _, name := range tests {
		t.Run(name, func(t *testing.T) {
			path := "testdata/regression/" + name + "/" + name

			in, err := os.Open(path + ".wasm")
			if err != nil {
				t.Fatal(err)
			}
			defer in.Close()

			if err := translate(in, io.Discard); err != nil {
				t.Fatal(err)
			}
		})
	}
}

func Test_translateSpecTest(t *testing.T) {
	*nanbox = true
	filepath.WalkDir("internal/spectest/", func(path string, d fs.DirEntry, err error) error {
		if d.IsDir() {
			if !*unsafe && strings.HasSuffix(path, "/threads") {
				return filepath.SkipDir
			}
			return nil
		}
		if ext := filepath.Ext(path); ext == ".wasm" {
			in, err := os.Open(path)
			if err != nil {
				t.Errorf("%s: %v", path, err)
				return nil
			}
			defer in.Close()

			var out bytes.Buffer
			err = translate(in, &out)
			if err != nil {
				t.Errorf("%s: %v", path, err)
				return nil
			}

			err = os.WriteFile(strings.TrimRight(path, ext)+".go", out.Bytes(), 0644)
			if err != nil {
				t.Errorf("%s: %v", path, err)
				return nil
			}

			err = generateSpecTest(path)
			if err != nil {
				t.Errorf("%s: %v", path, err)
				return nil
			}
		}
		return nil
	})
}

func generateSpecTest(path string) error {
	dir := filepath.Dir(path)
	baseDir := filepath.Base(dir)
	wasmFile := filepath.Base(path)
	jsonFile := baseDir + ".json"
	testFile := filepath.Join(dir, "gen_test.go")

	if _, err := os.Stat(filepath.Join(dir, baseDir+".json")); errors.Is(err, fs.ErrNotExist) {
		return nil
	}

	type specFileInfo struct {
		ImportPath string
		JSONFile   string
		WasmFile   string
	}

	info := specFileInfo{
		ImportPath: "github.com/ncruces/wasm2go/" + dir,
		JSONFile:   jsonFile,
		WasmFile:   wasmFile,
	}

	tmpl, err := template.New("spectest").Parse(specTestTemplate)
	if err != nil {
		return err
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, info); err != nil {
		return err
	}

	src, err := format.Source(buf.Bytes())
	if err != nil {
		return err
	}

	return os.WriteFile(testFile, src, 0644)
}

const specTestTemplate = `// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

import (
	_ "embed"
	"testing"

	"github.com/ncruces/wasm2go/internal/spectest"
)

//go:embed {{.JSONFile}}
var data []byte

func Test(t *testing.T) {
	spectest.Test(t, New(), data, "{{.WasmFile}}")
}
`
