// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

import "encoding/binary"

type Module struct {
	memory []byte
	maxMem int64
}

func New() *Module {
	m := new(Module)
	m.maxMem = 65536
	m.memory = make([]byte, 65536)
	return m
}
func (m *Module) fn0() int32 {
	t0 := int32(memory_grow(&m.memory, int64(i32(1)), m.maxMem))
	_ = t0
	return i32(12345)
}
func (m *Module) Xtest() int32 {
	t0 := m.fn0()
	store32(m.memory[uint32(i32(0)):], uint32(t0))
	t1 := int32(load32(m.memory[uint32(i32(0)):]))
	return t1
}
func (m *Module) Xsize() int32 {
	t0 := int32(len(m.memory) >> 16)
	return t0
}

//go:nosplit
func i32(x int32) int32 { return x }

//go:nosplit
func load32(b []byte) uint32 {
	return binary.LittleEndian.Uint32(b)
}

//go:nosplit
func store32(b []byte, v uint32) {
	binary.LittleEndian.PutUint32(b, v)
}

func memory_grow(mem *[]byte, delta, max int64) int64 {
	buf := *mem
	len := len(buf)
	old := int64(len) >> 16
	if delta == 0 {
		return old
	}
	new := old + delta
	add := int(new)<<16 - len
	if new > max || add < 0 {
		return -1
	}
	*mem = append(buf, make([]byte, add)...)
	return old
}
