// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

import (
	"encoding/binary"
	"math"
)

type Module struct {
	memory []byte
	maxMem int64
}

func New() *Module {
	m := new(Module)
	m.maxMem = 100
	m.memory = make([]byte, 65536)
	copy(m.memory[uint32(i32(0)):], data0)
	return m
}

type Memory = interface {
	Slice() *[]byte
	Grow(delta, max int64) int64
}
type wasmMemory []byte

func (m *wasmMemory) Slice() *[]byte {
	return (*[]byte)(m)
}
func (m *wasmMemory) Grow(delta, max int64) int64 {
	return memory_grow((*[]byte)(m), delta, max)
}
func (m *Module) Xwasm_grow(v0 int32) int32 {
	t0 := int32(memory_grow(&m.memory, int64(v0), m.maxMem))
	return t0
}
func (m *Module) Xwasm_size() int32 {
	t0 := int32(len(m.memory) >> 16)
	return t0
}
func (m *Module) Xwasm_fill(v0, v1, v2 int32) {
	memory_fill(m.memory, uint32(v0), v1, uint32(v2))
}
func (m *Module) Xread_as_i32(v0 int32) int32 {
	t0 := int32(load32(m.memory[uint32(v0):]))
	return t0
}
func (m *Module) Xread_as_i8u(v0 int32) int32 {
	t0 := int32(m.memory[uint32(v0)])
	return t0
}
func (m *Module) Xmemory() Memory {
	return (*wasmMemory)(&m.memory)
}

//go:nosplit
func i32(x int32) int32 { return x }

//go:nosplit
func load32(b []byte) uint32 {
	return binary.LittleEndian.Uint32(b)
}

func memory_grow(mem *[]byte, delta, max int64) int64 {
	buf := *mem
	len := len(buf)
	old := int64(len) >> 16
	if delta == 0 {
		return old
	}
	new := old + delta
	add := int(new)<<16 - len
	if new > max || add < 0 {
		return -1
	}
	*mem = append(buf, make([]byte, add)...)
	return old
}

func memory_fill[T uint32 | uint64](mem []byte, dest T, val int32, n T) {
	x := uint(min(uint64(dest), math.MaxUint))
	y := x + uint(min(uint64(n), math.MaxUint))
	buf := mem[x:y]
	if len(buf) > 0 {
		buf[0] = byte(val)
		for i := 1; i < len(buf); {
			chunk := min(i, 8192)
			i += copy(buf[i:], buf[:chunk])
		}
	}
}

const data0 = "ghip\xaa\xff\xdf\xcb\x12\xa12\xb3\xa5\x1f\x01\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x03\x05\a\t\v\r\x0f"
