// Code generated by wasm2go. DO NOT EDIT.

package trig_wasm

import "math"

type Module struct {
	memory           []byte
	maxMem           int64
	___stack_pointer int32
}

func New() *Module {
	m := new(Module)
	m.maxMem = 65536
	m.memory = make([]byte, 65536)
	m.___stack_pointer = i32(65536)
	return m
}

type Memory = interface {
	Slice() *[]byte
	Grow(delta, max int64) int64
}
type wasmMemory []byte

func (m *wasmMemory) Slice() *[]byte {
	return (*[]byte)(m)
}
func (m *wasmMemory) Grow(delta, max int64) int64 {
	return memory_grow((*[]byte)(m), delta, max)
}
func (m *Module) Xsin(v0 float64) float64 {
	var v1 float64
	var v2 int64
	var v3 int32
	var v4 float64
	if v0 != float64(0) {
		goto l0
	}
	return v0
l0:
	v1 = math.Float64frombits(0x7ff8000000000000)
	if int64(math.Float64bits(v0))&i64(0x7fffffffffffffff) > i64(0x7fefffffffffffff) {
		goto l1
	}
	{
		v1 = float64(float64(v0*float64(0.6366197723675814)) + math.Copysign(float64(0.5), v0))
		if !(math.Abs(v1) < float64(0x1p+63)) {
			goto l2
		}
		t0 := i64_trunc_f64_s(v1)
		v2 = t0
		goto l3
	}
l2:
	v2 = i64(-0x8000000000000000)
l3:
	v1 = float64(v0 + float64(float64(v2)*float64(-1.5707963267948966)))
	v3 = i32(0)
l10:
	if math.Abs(v1) > float64(0x1p-27) {
		goto l4
	}
	v4 = float64(1)
l9:
	if v3 != 0 {
		goto l5
	}
	switch int32(v2) & i32(3) {
	case 1:
		goto l6
	case 2:
		goto l7
	case 3:
		goto l8
	default:
		goto l1
	}
l5:
	v3 = v3 + i32(-1)
	v0 = float64(v1 * v1)
	v1 = float64(v4 * v1)
	v1 = float64(v1 + v1)
	v4 = float64(float64(1) - float64(v0+v0))
	goto l9
l6:
	return v4
l7:
	return -v1
l8:
	v1 = -v4
	goto l1
l4:
	v3 = v3 + i32(1)
	v1 = float64(v1 * float64(0.5))
	goto l10
l1:
	return v1
}
func (m *Module) Xmemory() Memory {
	return (*wasmMemory)(&m.memory)
}

//go:nosplit
func i32(x int32) int32 { return x }

//go:nosplit
func i64(x int64) int64 { return x }

//go:nosplit
func i64_trunc_f64_s(f float64) int64 {
	x := math.Trunc(f)
	switch {
	case f != f:
		panic("invalid conversion to integer")
	case x < math.MinInt64 || x >= math.MaxInt64:
		panic("integer overflow")
	}
	return int64(x)
}

func memory_grow(mem *[]byte, delta, max int64) int64 {
	buf := *mem
	len := len(buf)
	old := int64(len) >> 16
	if delta == 0 {
		return old
	}
	new := old + delta
	add := int(new)<<16 - len
	if new > max || add < 0 {
		return -1
	}
	*mem = append(buf, make([]byte, add)...)
	return old
}
